services:
  postgres:
    container_name: nostrfi_postgre
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - nostrfi
    restart: unless-stopped
networks:
  nostrfi:
    driver: bridge
volumes:
  postgres: